services:
  frontend:
    build: ./frontend
    ports: ["3000:80"]
    depends_on: [api]
    restart: unless-stopped
    
  api:
    build: ./api
    ports: ["8000:8000"]
    env_file: .env
    environment:
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - S3_REGION=${S3_REGION}
      - R2_BUCKET=${S3_BUCKET}
    restart: unless-stopped
